### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by gamerhun21** [Danielhiversen/PyXiaomiGateway#76] opened 2018-05-22 23:53 UTC
{'model': 'sensor_cube.aqgl01', 'short_id': 383, 'sid': '158d00024866f9', 'data': '{"voltage":2955}', 'cmd': 'read_ack'}

**Comment by syssi** [comment] 2018-05-23 08:12
Duplicate of #74. This is already fixed. The device will be supported in HA 0.70.

**Closed by syssi** 2018-05-23 08:12 UTC
