### ISSUE TITLE
Unsupported device found (Aqara Magic Cube)

### ISSUE THREAD

**Issue by LordSpectre** [Danielhiversen/PyXiaomiGateway#80] opened 2018-06-01 16:42 UTC
Hello, as far I know, the Aqara Magic Cube should be supported, but my HA is not able to add it with the following error:

2018-06-01 18:39:21 ERROR (Thread-8) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'model': 'sensor_cube.aqgl01', 'short_id': 4066, 'sid': '158d000230e61e', 'cmd': 'read_ack', 'data': '{"voltage":3600}'}

**Comment by syssi** [comment] 2018-06-02 09:52
Which HA version do you use?

**Comment by LordSpectre** [comment] 2018-06-02 10:07
HA 0.69.1 I installed new xiaomi_aqara.py from here:
https://github.com/home-assistant/home-assistant
Now my HA discover the Cube, but automation doesn't work.

**Comment by LordSpectre** [comment] 2018-06-02 10:57
I'm using the follwoing gateway: https://it.gearbest.com/living-appliances/pp_344667.html?wid=1433363 and FW ver is: 1.4.1_155.0143

**Comment by syssi** [comment] 2018-06-02 11:05
This is the lumi v3. Just to make sure the cube events aren't available please try the following: 

Enable the debug log by

```
# configuration.yaml
logger:
  default: warn
  logs:
    xiaomi_gateway: debug
    homeassistant.components.xiaomi_aqara: debug
    homeassistant.components.binary_sensor.xiaomi_aqara: debug
```

Restart HA and move, shake or flip the cube. Please provide the content of your home-assistant.log. There should be some cube events. If the cube does provide only the battery voltage it's not supported right now.

**Comment by LordSpectre** [comment] 2018-06-02 11:40
Yep! only voltage! :(

```
2018-06-02 13:09:06 DEBUG (Thread-5) [xiaomi_gateway] _send_cmd resp << {'sid': '158d000230e61e', 'short_id': 4066, 'data': '{"voltage":2995}', 'model': 'sensor_cube.aqgl01', 'cmd': 'read_ack'}
2018-06-02 13:09:06 DEBUG (Thread-5) [xiaomi_gateway] Registering device 158d000230e61e, sensor_cube.aqgl01 as: binary_sensor
```

**Comment by syssi** [comment] 2018-06-02 11:46
I hope the device will be supported soon. Just give it another try if a new gateway firmware is available.

**Comment by LordSpectre** [comment] 2018-06-02 13:16
But wait, when you said "not supported" I thought you were referring to HA, am I wrong?
Because I can add the cube to Mi Home App without problem, and I can see the events in the gatway/cube logs:
http://i63.tinypic.com/9ba9zp.png
http://i68.tinypic.com/2w6b8d0.png

**Comment by syssi** [comment] 2018-06-02 13:54
No. The gateway exposes two APIs. The miIO API used by the MiHome app and the "local network protocol" based on multicast messages used by Home Assistant. The last one is always a bit behind.

**Comment by LordSpectre** [comment] 2018-06-02 14:35
Got it, thank you, so we have to wait for Gateway firmware update.

**Comment by LordSpectre** [comment] 2018-06-03 06:19
Got it, thank you, so we have to wait for Gateway firmware update.

**Comment by ewanrw** [comment] 2018-06-13 23:07
Anything I can do in terms of testing to assist? I have the lumi 3 and aqara cube

**Comment by MiguelAngelLV** [comment] 2018-06-14 18:11
I have a Gateway v2 and Aqara cube. Update last firmware version.

Home Assistant show the cube, but don't detected the actions.

**Comment by bastianbeggel** [comment] 2018-06-16 13:32
I have the same problem with the Aqara Cube. It shows up in home assistant but events are not recognized. 
Newest Firmware:  1.4.1_155.0143
HA: 0.70.1

Hope the problem will be fixed some time soon.

**Comment by AntoWkill** [comment] 2018-06-19 09:40
Same problem for me, Aqara qube is recognised form HA but i can't use it for automation.

**Comment by alvarea** [comment] 2018-06-22 05:47
Hi, the same here, waiting for a new gateway firmware for some weeks... 

Has someone explored a new option I've seen on HA community to use Xiaomi Aqara devices with a MQTT broker, a zigbee hub and no need to use the xiaomi gateway?

**Comment by Smandurlo** [comment] 2018-07-23 19:32
new firmware for the gateway released, 1.41_156.0143 but sadly still no triggers from the aqara cube :-(

**Comment by DNKROZ** [comment] 2018-07-24 22:59
Yes, same problem here, updated to 1.41_156.0143 (from 1.41_155.0143) but I still get no triggers at all from the gateway when the cube is used :/

**Comment by reggiedev** [comment] 2018-07-25 17:16
it seens ha donest get the correct data except voltage
ha:ver0.74 
cube:binary_sensor.cube_158d000231e718 
getway: lumi.gateway.v3

**Comment by digidude** [comment] 2018-07-26 18:56
Same. Same gateway firmware as @dnkroz - HA:ver 0.74.2.
Found it automatically, pulls back battery level on initial fetch

`2018-07-26 14:25:45 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd resp << {'cmd': 'get_id_list_ack', 'sid': '7811dcdf13d7', 'token': 'mNqj9ZDiIgjsFIxu', 'data': '["158d0002430695","158d0002229a58","158d000223bd0c","158d00020f5d4e","158d000237ad54","158d00024a4bae"]'}
2018-07-26 14:25:45 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd >> b'{"cmd":"read","sid":"158d00024a4bae"}'
2018-07-26 14:25:45 DEBUG (SyncWorker_0) [xiaomi_gateway] _send_cmd resp << {'cmd': 'read_ack', 'model': 'sensor_cube.aqgl01', 'sid': '158d00024a4bae', 'short_id': 12223, 'data': '{"voltage":2965}'}
2018-07-26 14:25:45 DEBUG (SyncWorker_0) [xiaomi_gateway] Registering device 158d00024a4bae, sensor_cube.aqgl01 as: binary_sensor`

Other sensors are coming through
`2018-07-26 14:25:44 INFO (SyncWorker_0) [homeassistant.components.xiaomi_aqara] Discovering Xiaomi Gateways (Try 1)
2018-07-26 14:25:50 DEBUG (SyncWorker_0) [homeassistant.components.xiaomi_aqara] Gateways discovered. Listening for broadcasts
2018-07-26 14:25:55 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.
2018-07-26 14:32:39 DEBUG (MainThread) [homeassistant.components.xiaomi_aqara] PUSH >> <Entity Motion Sensor_158d000237ad54: off>: {'lux': '162'}
2018-07-26 14:32:39 DEBUG (MainThread) [homeassistant.components.xiaomi_aqara] PUSH >> <Entity Illumination_158d000237ad54: 73.0>: {'lux': '162'}
2018-07-26 14:34:39 DEBUG (MainThread) [homeassistant.components.xiaomi_aqara] PUSH >> <Entity Motion Sensor_158d000237ad54: off>: {'no_motion': '120'}
2018-07-26 14:34:39 DEBUG (MainThread) [homeassistant.components.xiaomi_aqara] PUSH >> <Entity Illumination_158d000237ad54: 162.0>: {'no_motion': '120'}`

No love

**Comment by LucasKubicki** [comment] 2018-07-27 17:16
Same problem, new firmware and no states sent from the gateway to HA

**Comment by alphamax** [comment] 2018-07-28 09:32
Same here (just to be notified for updates :))

**Comment by bhchew** [comment] 2018-08-02 13:02
Anyway we can roll back the gateway firmware until there is a solution?

**Comment by syssi** [comment] 2018-08-02 13:05
There is no firmware in the wild which supports the new cube generation. Why do you want to roll back?

**Comment by digidude** [comment] 2018-08-02 13:10
@bgchew - you have to get the older version of the Cube - with the Mi logo on it, not the Aqara logo.

**Comment by bhchew** [comment] 2018-08-02 13:12
Ah ok, gotcha

Btw below might be worth mentioning, have not tried it though.

https://github.com/Koenkk/zigbee2mqtt

**Comment by digidude** [comment] 2018-08-02 13:17
Interesting project. Note that they too are very specific about supporting the Mi Cube - NOT the Aqara Cube.

**Comment by jamieshaw** [comment] 2018-08-02 18:49
So it looks like I pulled the trigger on a cube without seeing all this first. Tried to read through to see if a fix/update is in the works but couldn't find any confirmation — surely this just needs an update to an API somewhere? 🤔

**Comment by benleb** [comment] 2018-08-03 14:09
@digidude did where you read this?

the aqara cube (MFKZQ01LM) works with [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt) without problems, i checked it just now ;)

```2018-8-3 14:07:04 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"flip90","from_side":1,"to_side":5}'
2018-8-3 14:07:07 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"shake"}'
2018-8-3 14:07:11 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"rotate_left","angle":-123.32}'
2018-8-3 14:07:12 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"rotate_left","angle":-35.52}'
2018-8-3 14:07:18 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"slide","side":5}'
2018-8-3 14:07:28 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"flip180","side":2}'
2018-8-3 14:07:48 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d00027d1337', payload: '{"action":"fall"}'```

**Comment by jamieshaw** [comment] 2018-08-03 14:32
Thanks, and apologies, just trying to get up to speed.
Is it just that Xiaomi aren't advertising events via an API (or a new API)?

**Comment by benleb** [comment] 2018-08-03 14:51
@jamieshaw see https://github.com/Danielhiversen/PyXiaomiGateway/issues/80#issuecomment-394089281 from syssi

**Comment by jamieshaw** [comment] 2018-08-03 15:12
Got ya, thanks. I appreciate it it - just a waiting game then ¯\_(ツ)_/¯

**Comment by bhchew** [comment] 2018-08-04 02:40
@benlib

nice one =)

Been reading a bit on zigbee2mqtt, did you install the hassio add on? And are the hardware still required as mentioned below?

https://github.com/Koenkk/zigbee2mqtt/wiki/Getting-started

**Comment by benleb** [comment] 2018-08-04 10:13
@bhchew I am not using Hassio... 
Sure, some hardware is required as something musst receive the Zigbee packets

**Comment by psyhomb** [comment] 2018-08-05 17:12
Same problem on my side!

Gw fw: 1.4.1_156.0143

```
Aug 05 19:01:14 hass hass[8224]: 2018-08-05 19:01:14 ERROR (Thread-9) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d00026e9a28', 'short_id': 40798, 'model': 'sensor_cube.aqgl01', 'cmd': 'read_ack', 'data': '{"voltage":3015}'}
```

**Comment by psyhomb** [comment] 2018-08-05 18:42
Binary sensor has been detected after I upgraded Hass to the latest version (**0.69.1** => **0.75.1**), also I don't see previous error in my logs anymore!

Now I'll have to check if sensor is working properly by configuring some triggers in automation section.

```
Aug 05 20:31:42 hass hass[19927]: 2018-08-05 20:31:42 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: new_state=<state binary_sensor.cube_158d00026e9a28=off; last_action=None, friendly_name=Cube_158d00026e9a28, battery_level=39.0 @ 2018-08-05T20:31:42.729216+02:00>, entity_id=binary_sensor.cube_158d00026e9a28, old_state=None>
```

Tho it is a bit strange that my battery level is 39%, given that this is a new cube that just arrived from China?

**Comment by benleb** [comment] 2018-08-05 18:53
@psyhomb maybe you should read all the comments here. your cube does not work, it just shows you the battery state...

and 39%... thats more or less normal I would say from my experience, it’s a cheap china sensor... but it decreases very slowly in return ;)

**Comment by psyhomb** [comment] 2018-08-05 19:17
Thanks for the info @benleb.

Yes I already read all the comments, but I wanted to be sure myself that things are like you all said :wink:, and they are, definitely lack of support on the API side, sensor still doesn't work!

**Comment by benleb** [comment] 2018-08-05 19:42
yea, dont trust, try it yourself :1:

**Comment by syssi** [comment] 2018-08-25 20:55
It looks like the cube will be supported by fw 1.4.1_157.0143.

**Comment by h4nc** [comment] 2018-08-25 23:08
I can confirm that.

Cube works now in HA.

Firmware 1.4.1_157.0143

**Closed** 2018-08-26 06:36 UTC

**Comment by jamieshaw** [comment] 2018-08-27 06:43
Is this firmware available? I’m not seeing it as an option, running the Mainland China locale.

**Comment by giangvo** [comment] 2018-08-27 06:46
Yup, I am using the Mainland China locale and the new version is available and the cube works with HA in the new version.
Cheers,

**Comment by jamieshaw** [comment] 2018-08-27 06:58
Huh, checking for updates only shows me 1.4.1_156.0143.

Not using a proxy or anything, could that be the case? 🤔

**Comment by LordSpectre** [comment] 2018-08-27 07:33
Same for me, stuck at 1.4.1_156.0143 with no update. I'll wait for update and try again

**Comment by digidude** [comment] 2018-08-27 19:06
Same. Stuck at 1.4.1_156.0143. Holding breath....turning blue....

**Comment by michbaeck** [comment] 2018-08-27 19:39
Has anyone tried with with the new homekit capable gateway? Is it even supported already?

Von meinem iPhone gesendet

**Comment by alphamax** [comment] 2018-08-28 08:42
FYI, Update done yesterday (v1.4.1_157...)
And i have now the cube data on my home assistant

![image](https://user-images.githubusercontent.com/10722632/44711603-02eec000-aaaf-11e8-9f3a-3e0f1d80e2b2.png)

**Comment by MiguelAngelLV** [comment] 2018-08-28 09:02
Any way to force update? I don't have the update in my Mi Home :(

**Comment by michbaeck** [comment] 2018-08-28 10:35
me neither. But I am waiting for months, I'll survive a couple of days/weeks on top

Von meinem iPhone gesendet

**Comment by syssi** [comment] 2018-08-28 21:06
![screenshot_mi_home_20180828-225504](https://user-images.githubusercontent.com/2735933/44750857-dcfd0600-ab16-11e8-805d-779bd0012ae6.png)

**Comment by jamieshaw** [comment] 2018-08-29 04:55
It’s appearing for me now on iOS. 👍🏻

**Comment by bastianbeggel** [comment] 2018-08-29 18:11
I have the new firmware (v1.4.1_157....) and I have HA 0.77.0.
The cube only produces rotate events in my setting. No luck with flip90 or any of the other events. 
Can anybody confirm that all event types are working? With which version of HA?

**Comment by michbaeck** [comment] 2018-08-29 18:27
just updated the GW and it's working for me on **0.76.1**
![image](https://user-images.githubusercontent.com/41584665/44807395-c2d03000-abc9-11e8-9504-dfbe44ed9e7f.png)

Can anyone confirm it should run on 0.77 as well (before I update ;).
Also, how is action "alert" triggered?

**Comment by michbaeck** [comment] 2018-08-29 18:29
lol, just took the wrong screen. Other actions than "rotate" work as well
![image](https://user-images.githubusercontent.com/41584665/44807593-3d994b00-abca-11e8-9df2-91aaf73b0df6.png)

**Comment by bastianbeggel** [comment] 2018-08-29 18:36
Thanks for the info. 
I think the problem is that I have a different cube. My aqara cube only supports 6 events (free_fall not being one of these 6 actions). Bad luck for me.

**Comment by bstrakt** [comment] 2018-08-29 18:53
I can confirm that all gestures works with the new firmware (v1.4.1_157....) and HA 0.76.2
After updating to 0.77 the cube only registers Rotate (and only once).
I have downgraded to 0.76.2 until it's fixed

**Comment by syssi** [comment] 2018-08-29 19:01
@bstrakt Thanks for the hint. In this case I broke it. I will care about a fix!

**Comment by michbaeck** [comment] 2018-08-29 19:02
@bastianbeggel no worries, I have the same model. It's probably just the HA version as @bstrakt confirmed.

wow...I just realize this thing can be used to control my home entirely. I action to switch mode (climate, music, light,...) another to switch rooms and others to control...that's awesome

**Comment by michbaeck** [comment] 2018-08-29 19:26
@syssi awseome! that was quick.

this might be helpful for someone to use all functions with a single automation
```yaml
- id: 'cube_test'
  alias: 'cube_test'
  trigger:
    - platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.xiaomi_cube
  action:
    # uncomment lines below for debugging
    - service: persistent_notification.dismiss
      data_template:
        notification_id: 'cube_test'
    - service: persistent_notification.create
      data_template:
        notification_id: 'cube_test'
        title: >-
          'cube_test'
        message: >-
          {{"TYPE: " + trigger.event.data.action_type|string }}
          {{"VALUE: "}}{{ trigger.event.data.action_value|default(0)|float }}
    # uncomment lines above for debugging
    - service_template: >-
        {#- call script.cube_move, script.cube_rotate, etc. and pass action_value as parameter -#}
        {{ "script.cube_" + trigger.event.data.action_type|string }}
      data_template:
        value: >-
          {{ trigger.event.data.action_value|default(0)|float }}
```

**Comment by bastianbeggel** [comment] 2018-08-30 06:33
@syssi : I applied you patch manually to my installation of HA 0.77 by:
sudo su - homeassistant -c "nano /srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/binary_sensor/xiaomi_aqara.py".

Now I am seeing all event. Thanks for the quick help.

**Comment by bstrakt** [comment] 2018-08-30 06:34
Thanks @syssi for the quick fix. I have installed 0.77.1 and the action is registered in the cube binary sensor, but it says unknown in template sensor created to show the last cube state in the UI. Also, automations don't trigger based on th3 cube action (for example shake_air is registered, but no automation triggers). I have also deleted the database and downgraded to 0.76.2 which works as it should. Tried another update to 0.77.1 after deleting the database, but still no automation triggers and no statu update for the template sensot. I did not see any braking changes regarding aqara platform or template sensor. There must be something related to xiaomi platform in the new version.

**Comment by syssi** [comment] 2018-08-30 06:50
Please share your configuration.

**Comment by bstrakt** [comment] 2018-08-30 07:10
Here is the template sensor config (working in 0.76.2 but not in 0.77.1):
`- platform: template
    sensors:
      cube_last_state:
        friendly_name: "Living Room Cube"
        value_template: "{{ states.binary_sensor.cube_xxxxxxxxxxx.attributes.last_action }}"`
and automation:
`- alias: Cube event shake_air
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_xxxxxxxxxxx
      action_type: shake_air
  action:
    - service: script.turn_on
      entity_id: script.watchtvliving`
The automation runs if I manually try with automation.trigger service in UI.
This is the state for the template sensor in HA 0.76.2:
![image](https://user-images.githubusercontent.com/7382687/44835353-aa4d2d80-ac3c-11e8-8080-9bce922bb244.png)
In 0.77.1 it displays Unknown, altough the the cube binary sensor displays the last action correctly.

**Comment by bastianbeggel** [comment] 2018-08-30 07:13
@bstrakt : I had something stange in my configuration. The ID of my cube changed from binary_sensor.cube_xxxxxxxxxxx to binary_sensor.cube_xxxxxxxxxxx_2 while the friendly name still being binary_sensor.cube_xxxxxxxxxxx. 
That is why my automation were also not working at the beginning. But it is easy to see in the logs or in the dev-state tab. Maybe its worth checking.

**Comment by bstrakt** [comment] 2018-08-30 07:31
Thanks @bastianbeggel, that was the problem 👍 . It seems I was too lazy to debug :D
